# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-06 13:56
from __future__ import unicode_literals

from django.db import migrations, models
import govweb.common


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', govweb.common.BigAutoField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=400)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
