# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-06 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('govweb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='creation_date',
            field=models.DateTimeField(default=''),
        ),
    ]
