# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-06 14:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('govweb', '0002_auto_20190306_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='creation_date',
        ),
    ]
