# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-06 14:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('govweb', '0003_remove_student_creation_date'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table='STUDENT',
        ),
    ]
